import type { PlanConfig, PlanSlug } from '@/types'

export const PLANS: Record<PlanSlug, PlanConfig> = {
  free: {
    name: 'Gratuit',
    slug: 'free',
    maxSearchesLifetime: 3,
    maxResultsPerSearch: 10,
    visibleResults: 3,
    maxProspects: 5,
    canExport: false,
    hasCRM: false,
    hasAnalysis: false,
    hasOutreach: false,
    hasClients: false,
    hasPortfolio: false,
    hasRevenue: false,
    hasAlerts: false,
    hasWatchlists: false,
    priceMonthly: 0,
  },
  pro: {
    name: 'Pro',
    slug: 'pro',
    maxSearchesLifetime: Infinity,
    maxResultsPerSearch: 50,
    visibleResults: 50,
    maxProspects: Infinity,
    canExport: true,
    hasCRM: true,
    hasAnalysis: false,
    hasOutreach: true,
    hasClients: true,
    hasPortfolio: false,
    hasRevenue: false,
    hasAlerts: false,
    hasWatchlists: true,
    priceMonthly: 14.99,
    stripePriceId: process.env.STRIPE_PRO_PRICE_ID,
  },
  business: {
    name: 'Business',
    slug: 'business',
    maxSearchesLifetime: Infinity,
    maxResultsPerSearch: 50,
    visibleResults: 50,
    maxProspects: Infinity,
    canExport: true,
    hasCRM: true,
    hasAnalysis: true,
    hasOutreach: true,
    hasClients: true,
    hasPortfolio: true,
    hasRevenue: true,
    hasAlerts: true,
    hasWatchlists: true,
    priceMonthly: 44.99,
    stripePriceId: process.env.STRIPE_BUSINESS_PRICE_ID,
  },
}

export const PROSPECT_STATUSES = [
  { value: 'decouvert', label: 'Découvert', emoji: '🔍', color: 'bg-blue-100 text-blue-800' },
  { value: 'contacte', label: 'Contacté', emoji: '📧', color: 'bg-yellow-100 text-yellow-800' },
  { value: 'negociation', label: 'Négociation', emoji: '🤝', color: 'bg-purple-100 text-purple-800' },
  { value: 'client', label: 'Client', emoji: '✅', color: 'bg-green-100 text-green-800' },
  { value: 'perdu', label: 'Perdu', emoji: '❌', color: 'bg-red-100 text-red-800' },
] as const

export const DELIVERABLE_STATUSES = [
  { value: 'a_faire', label: 'À faire', color: 'bg-gray-100 text-gray-800' },
  { value: 'en_cours', label: 'En cours', color: 'bg-blue-100 text-blue-800' },
  { value: 'en_revision', label: 'En révision', color: 'bg-yellow-100 text-yellow-800' },
  { value: 'valide', label: 'Validé', color: 'bg-green-100 text-green-800' },
  { value: 'livre', label: 'Livré', color: 'bg-emerald-100 text-emerald-800' },
] as const

export const PRIORITY_CONFIG = {
  low: { label: 'Basse', color: 'bg-gray-100 text-gray-600', dot: 'bg-gray-400' },
  medium: { label: 'Moyenne', color: 'bg-blue-100 text-blue-600', dot: 'bg-blue-400' },
  high: { label: 'Haute', color: 'bg-orange-100 text-orange-600', dot: 'bg-orange-400' },
  urgent: { label: 'Urgente', color: 'bg-red-100 text-red-600', dot: 'bg-red-400' },
} as const

export const NICHE_LABELS: Record<string, string> = {
  gaming: 'Gaming',
  tech: 'Tech',
  business: 'Business',
  finance: 'Finance',
  crypto: 'Crypto',
  lifestyle: 'Lifestyle',
  fitness: 'Fitness',
  cooking: 'Cuisine',
  travel: 'Voyage',
  education: 'Éducation',
  entertainment: 'Divertissement',
  music: 'Musique',
  comedy: 'Comédie',
  vlog: 'Vlog',
  beauty: 'Beauté',
  fashion: 'Mode',
  sports: 'Sport',
  science: 'Science',
  news: 'Actualités',
  real_estate: 'Immobilier',
  marketing: 'Marketing',
  coaching: 'Coaching',
  kids: 'Enfants',
  diy: 'DIY',
  automotive: 'Automobile',
  photography: 'Photo',
  art: 'Art',
  health: 'Santé',
  motivation: 'Motivation',
  other: 'Autre',
}

export const APP_NAME = 'MiniaMaker'
export const APP_DESCRIPTION = 'La plateforme de prospection pour les créateurs de miniatures YouTube'
